#!/usr/bin/env bash
# Rewrite PKGBUILD for the latest Delta release. Building/installing is left to paru.
# Source is zed-industries/delta-nix (published by Zed's release bot): permanent
# GitHub Release URLs plus SRI hashes in releases.json. delta.dev's own API only hands
# out 15-minute signed URLs for the latest build and no checksum, which a PKGBUILD
# can't pin. Both serve byte-identical tarballs (checked for 0.17.0).
set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")"

json=$(curl -fsSL https://raw.githubusercontent.com/zed-industries/delta-nix/HEAD/releases.json)

# -e: fail on a missing key instead of writing "null" into the PKGBUILD
field() { jq -er ".stable.$1" <<<"$json"; }
tag=$(field tag)
pkgver=$(field version | tr - _)

# SRI "sha256-<base64>" -> hex, as makepkg expects
sri_to_hex() { base64 -d <<<"${1#sha256-}" | od -An -vtx1 | tr -d ' \n'; }
sum_x86_64=$(sri_to_hex "$(field 'systems["x86_64-linux"].hash')")
sum_aarch64=$(sri_to_hex "$(field 'systems["aarch64-linux"].hash')")

cat >PKGBUILD <<EOF
# Generated by bump.sh from delta-nix releases.json — edit bump.sh, not this file.
pkgname=zed-delta-bin
pkgver=$pkgver
pkgrel=1
pkgdesc="Delta - AI-native code editor from Zed (prebuilt binary)"
arch=('x86_64' 'aarch64')
url="https://delta.dev"
license=('custom')
depends=('glibc' 'hicolor-icon-theme')
provides=('zed-delta')
conflicts=('zed-delta' 'git-delta')
options=('!strip' '!debug')
_rel="https://github.com/zed-industries/delta-nix/releases/download/$tag"
source_x86_64=("delta-\$pkgver-x86_64.tar.gz::\$_rel/delta-linux-x86_64.tar.gz")
source_aarch64=("delta-\$pkgver-aarch64.tar.gz::\$_rel/delta-linux-aarch64.tar.gz")
sha256sums_x86_64=('$sum_x86_64')
sha256sums_aarch64=('$sum_aarch64')

package() {
  install -d "\$pkgdir/opt/delta" "\$pkgdir/usr/bin" "\$pkgdir/usr/share"
  cp -a "\$srcdir/Delta/bin" "\$srcdir/Delta/lib" "\$pkgdir/opt/delta/"
  ln -s /opt/delta/bin/delta "\$pkgdir/usr/bin/delta"
  cp -a "\$srcdir/Delta/share/applications" "\$srcdir/Delta/share/icons" "\$pkgdir/usr/share/"
}
EOF

echo "zed-delta-bin -> $pkgver ($tag)"
